"""Deterministic Phase 9 research synthesis domain."""

from .contracts import (
    SECTION_ORDER,
    CitationSourceContext,
    ClaimDisposition,
    ConfidenceLabel,
    FreshnessClassification,
    LanguagePreference,
    MaterialClaimKind,
    MissingDataReason,
    OutputLanguage,
    ResearchSectionType,
    SynthesisId,
    SynthesisStatus,
    VerifiedClaimInput,
)
from .model import (
    CitationReference,
    ConfidenceContext,
    ContradictionContext,
    ExecutiveSummary,
    ExecutiveSummaryItem,
    FreshnessContext,
    MissingDataContext,
    ResearchClaim,
    ResearchDocument,
    ResearchSection,
    ResearchSynthesis,
)
from .policy import DeterministicSynthesisAssembler, VerifiedClaimGate

__all__ = [
    "SECTION_ORDER",
    "CitationReference",
    "CitationSourceContext",
    "ClaimDisposition",
    "ConfidenceContext",
    "ConfidenceLabel",
    "ContradictionContext",
    "DeterministicSynthesisAssembler",
    "ExecutiveSummary",
    "ExecutiveSummaryItem",
    "FreshnessClassification",
    "FreshnessContext",
    "LanguagePreference",
    "MaterialClaimKind",
    "MissingDataContext",
    "MissingDataReason",
    "OutputLanguage",
    "ResearchClaim",
    "ResearchDocument",
    "ResearchSection",
    "ResearchSectionType",
    "ResearchSynthesis",
    "SynthesisId",
    "SynthesisStatus",
    "VerifiedClaimGate",
    "VerifiedClaimInput",
]
